<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProfesionesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $profesiones = [
            "abogado",
            "actor",
            "administración de aduana",
            "administración de desastres gestión riesgo",
            "administración de empresas",
            "agricultor",
            "albañil",
            "anfitriona",
            "arquitecto",
            "atleta",
            "auxiliar de enfermería",
            "bachiller",
            "bailarín",
            "barbero",
            "basquetbolista",
            "beisbolista",
            "bibliotecario",
            "bombero",
            "cajero",
            "carnicero",
            "carpintero",
            "cocinero",
            "comerciante",
            "costurero (a)",
            "custodio",
            "ebanista",
            "escolta",
            "escritor",
            "estética",
            "florista",
            "fontanero",
            "funcionario público",
            "futbolista",
            "geógrafo",
            "geólogo",
            "ingeniería agrónoma",
            "ingeniería agroalimentación",
            "ingeniería civil",
            "ingeniería de telecomunicaciones",
            "ingeniería electricista",
            "ingeniería en agroalimentación",
            "ingeniería en informática",
            "ingeniería en petróleo",
            "ingeniería en química",
            "ingeniería en sistemas",
            "ingeniería física",
            "ingeniería industrial",
            "ingeniería mecánica",
            "ingeniería química",
            "jardinero",
            "jefe de cocina (chef)",
            "licenciatura en acuacultura",
            "licenciatura en administración comercial",
            "licenciatura en administración de procesamientos de datos",
            "licenciatura en administración de recursos humanos",
            "licenciatura en administración mención gerencia empresarial",
            "licenciatura en administración mención informática",
            "licenciatura en administración mención recursos humanos",
            "licenciatura en administración pública",
            "licenciatura en banca y finanzas",
            "licenciatura en bioanálisis",
            "licenciatura en biología",
            "licenciatura en biología marina",
            "licenciatura en ciencia política",
            "licenciatura en ciencias penales y criminológicas",
            "licenciatura en ciencias policiales",
            "licenciatura en comunicación social",
            "licenciatura en comunicación social (periodista)",
            "licenciatura en contaduría pública",
            "licenciatura en derecho tributario",
            "licenciatura en diseño gráfico",
            "licenciatura en economía",
            "licenciatura en educación especial",
            "licenciatura en educación integral",
            "licenciatura en educación mención ciencias sociales",
            "licenciatura en estudios internacionales",
            "licenciatura en estudios políticos de gobierno",
            "licenciatura en farmacia",
            "licenciatura en finanzas",
            "licenciatura en gerencia de programas sociales",
            "licenciatura en gerencia financiera",
            "licenciatura en gestión social",
            "licenciatura en idiomas",
            "licenciatura en informática",
            "licenciatura en investigación penal",
            "licenciatura en matemática",
            "licenciatura en organización y métodos",
            "licenciatura en psicología",
            "licenciatura en publicidad y mercadeo",
            "licenciatura en trabajo social",
            "licenciatura en turismo",
            "manicurista",
            "maquillador",
            "mecánico",
            "médico",
            "médico anestesiólogo",
            "médico cardiólogo",
            "médico cirujano",
            "médico fisioterapeuta",
            "médico foniatra",
            "médico forense",
            "médico ginecólogo",
            "médico neumólogo",
            "médico oftalmólogo",
            "médico oncólogo",
            "médico patólogo",
            "médico pediatra",
            "médico psiquiatra",
            "médico veterinario",
            "mensajero",
            "mesonero",
            "militar",
            "modelo",
            "músico",
            "niñera",
            "obrero",
            "panadero",
            "peluquero (a)",
            "pescador",
            "piloto",
            "pintor",
            "plomero",
            "policía",
            "politólogo",
            "recepcionista",
            "repostero",
            "sacerdote",
            "salvavidas",
            "sastre",
            "secretaria",
            "seguridad",
            "sobrecargo",
            "sociología",
            "taxista",
            "técnico electricista",
            "técnico en publicidad y mercadeo",
            "técnico medio en comercio y servicios administrativos",
            "técnico medio en comercio y servicios administrativos mención informática",
            "técnico medio en refrigeración",
            "técnico medio en telecomunicaciones",
            "técnico superior en administración",
            "técnico superior en administración de empresas",
            "técnico superior en informática",
            "técnico superior en relaciones públicas",
            "técnico superior universitario",
            "técnico superior universitario en administración",
            "técnico superior universitario en administración de personal",
            "técnico superior universitario en administración de recursos humanos",
            "técnico superior universitario en administración tributaria",
            "técnico superior universitario en ciencias audiovisuales y fotografía",
            "técnico superior universitario en comercio exterior",
            "técnico superior universitario en diseño gráfico",
            "técnico superior universitario en educación inicial",
            "técnico superior universitario en educación integral",
            "técnico superior universitario en enfermería",
            "técnico superior universitario en estudios penitenciarios",
            "técnico superior universitario en higiene y seguridad industrial",
            "técnico superior universitario en informática",
            "técnico superior universitario en mercadeo",
            "técnico superior universitario en mercadeo con mención publicidad",
            "técnico superior universitario en preescolar",
            "técnico superior universitario en publicidad",
            "técnico superior universitario en publicidad y mercadeo",
            "técnico superior universitario en relaciones industriales",
            "técnico superior universitario en riesgo y seguro",
            "técnico superior universitario en tecnología de la construcción civil",
            "técnico superior universitario en trabajo social",
            "traductor",
            "vigilante",
        ];

        foreach ($profesiones as $nombre) {
            DB::table('profesiones')->insert([
                'nombre' => $nombre,
            ]);
        }
    }
}
